comment out format check and lint check

diff --git a/.github/workflows/test-ci.yml b/.github/workflows/test-ci.yml
--- a/.github/workflows/test-ci.yml
+++ b/.github/workflows/test-ci.yml
@@ -20,11 +20,11 @@ jobs:
     - name: npm install
       run: npm ci
 
-    - name: check if formatted
-      run: npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0mProject is not formatted. Please run "npm run format".' && false)
+    # - name: check if formatted
+    #   run: npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0mProject is not formatted. Please run "npm run format".' && false)
 
-    - name: check lint
-      run: npm run lint
+    # - name: check lint
+    #   run: npm run lint
 
     - name: build tests
       run: npm run buid:tests
